---
- name: Create Admin service account
  oc_serviceaccount:
    name: kuryr-controller
    namespace: "{{ kuryr_namespace }}"
  register: saout

- name: Create a role for the Kuryr controller
  oc_clusterrole:
    name: kuryrctl
    state: present
    rules:
      - apiGroups:
        - ""
        attributeRestrictions: null
        verbs:
          - get
          - list
          - watch
        resources:
          - daemonsets
          - deployments
          - deploymentconfigs
          - endpoints
          - ingress
          - nodes
          - namespaces
          - pods
          - projects
          - routes
          - services
      - apiGroups:
        - ""
        attributeRestrictions: null
        verbs:
          - update
          - patch
        resources:
          - endpoints
          - ingress
          - pods
          - namespaces
          - nodes
          - services
          - services/status
          - routes

- name: Fetch the created Kuryr controller cluster role
  oc_clusterrole:
    name: kuryrctl
    state: list
  register: crout

- name: Grant Kuryr the anyuid security context constraints
  oc_adm_policy_user:
    user: "system:serviceaccount:{{ kuryr_namespace }}:{{ saout.results.results.0.metadata.name }}"
    namespace: "{{ kuryr_namespace }}"
    resource_kind: scc
    resource_name: anyuid
    state: present

- name: Grant Kuryr the privileged security context constraints
  oc_adm_policy_user:
    user: "system:serviceaccount:{{ kuryr_namespace }}:{{ saout.results.results.0.metadata.name }}"
    namespace: "{{ kuryr_namespace }}"
    resource_kind: scc
    resource_name: privileged
    state: present

- name: Assign role to Kuryr service account
  oc_adm_policy_user:
    user: "system:serviceaccount:{{ kuryr_namespace }}:{{ saout.results.results.0.metadata.name }}"
    namespace: "{{ kuryr_namespace }}"
    resource_kind: cluster-role
    resource_name: "{{ crout.results.results.metadata.name }}"
    state: present
